version: "3.1"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    env_file: .env
    deploy:
      mode: global
  web:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "5001:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    deploy:
      placement:
        constraints: [node.role == manager]
