---
- set_fact:
     current_host: "{{ ansible_host }}"

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if necessary
  shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

## IMPORTANT: Set the proper Localhost python binary location  ie: /usr/bin/python3 ##
- name: Wait for the server to finish rebooting
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  become: no
  local_action: wait_for host={{ current_host }} state=started port={{ ansible_port }} delay=30 timeout=120
  when: reboot_required_file.stat.exists

- name: Pause for SSH to come alive
  pause: seconds=15
  when: reboot_required_file.stat.exists

- name: Get Uptime
  shell: uptime
  register: uptime_result

- debug: msg="{{ uptime_result.stdout }}"
